/glg4debug/glg4param omit_muon_processes  1.0
/glg4debug/glg4param omit_hadronic_processes  1.0

#set the d parameters
/rat/db/set DETECTOR experiment "NuLat"
/rat/db/load /home/jack/RATPAC2/ratpac-setup/ratpac/NuLat/ratdb/MATERIALS_NULAT.ratdb
/rat/db/load /home/jack/RATPAC2/ratpac-setup/ratpac/NuLat/ratdb/PMT_NULAT.ratdb
/rat/db/set DETECTOR geo_file "/home/jack/RATPAC2/ratpac-setup/ratpac/NuLat/data/NULAT5x5x5_instrumented_Li6.geo"

/tracking/storeTrajectory 1
/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"

/run/initialize

/rat/proc count
/rat/procset update 1000

# Use IO.default_output_filename
/rat/proc outroot
/rat/procset file "sodium_22_decay_test_1.root"
## OUTPUT PYTHON-LIKE FORMAT
/rat/proc outntuple
/rat/procset include_tracking 1
/rat/procset include_mcparticles 1
/rat/procset include_pmthits 1
/rat/procset include_untriggered_events 1

##### GENERATORS #################
/generator/add combo gun:point
/generator/vtx/set gamma 0 0 0 1.274
/generator/vtx/set eplus 0 0 0 0.0
/generator/pos/set -180 0 0

##### RUN ###########
/run/beamOn 500000
