import os
import sys
import time as timer
import random
import json
import math
import pandas as pd
import numpy as np
import glob
import subprocess

class createNuLatFiducialSet():
    """
    CreateNuLatFiducialSet class for use on processed RATPAC2 output files for NuLat reference data to be binned for FND fits.
    This code reads the ASCII data files generated by process_fiducial_data.sh, and bins the events in (normalized) 
    directional matrices based on the relative displacement between the positron annihilation (prompt) and 
    neutron capture (delayed) events within the segmented geometry. For use in directory containing fiducial data set ROOT files.
    """

    def __init__(self):
        """
        Initializes class and creates an instance with defined parameters
        Args:
            None.
        Return values:
            None.
        """
        # control Booleans
        self.debug = False
        self.time_start = timer.time() # only use when self.debug == True
        # debugging message
        if(self.debug):
            print("CreateNuLatFiducialSet class initialized")
        self.exit_err_msg = "Quitting without binning fiducial set..."
        # data processing objects and variables
        self.alpha_code = 1000020040
        self.triton_code = 1000010030
        # Data Directories
        self.data_dir = os.getcwd()
        self.output_file = os.path.join(self.data_dir, "nulat_fiducial_directionality_set.json")
        self.results = {"metadata": {"description": "5x5 Directional Matrices", "axes": "Delta X, Y (Delayed - Prompt)", "note": "Out-of-bounds matrices dropped"}, "angles": {}}
        self.macro_path = os.path.join(self.data_dir, "readFiducial.C")
	# Detector Geometry Parameters (Must match simulation)
        self.inch = 25.4
        self.cube_size = 2.5 * self.inch      # 63.5 mm
        self.gap_size = 0.001 * self.inch     # 0.0254 mm
        self.step_size = self.cube_size + self.gap_size
        self.grid_dim = 5
        total_span = self.grid_dim * self.step_size - self.gap_size
        self.offset = -total_span / 2.0 + self.cube_size / 2.0
        return

    def configure(self):
        """
        Detect files and prompt user for configuration.
        Args:
            None.
        Return values:
            None.
        """
        root_files = glob.glob(os.path.join(self.data_dir, "nulat_output_angle_*.ntuple.root"))
        root_files.sort()
        print("\n--- NuLat Physics Fiducial Directionality Matrix Calculator Configuration ---")
        if not root_files:
            print("No 'nulat_output_angle_*.ntuple.root' files found in current directory.\nCheck your current working directory and move files as necessary.\nExiting...")
            sys.exit(0)
        elif self.debug:
            print("ROOT files found:")
            for i, f in enumerate(root_files):
                print(f"  [{i+1}] {os.path.basename(f)}")
        # Check for an existing JSON file and prompt the user for overwrite
        if os.path.exists(self.output_file):
            print(f"WARNING: Output file already exists at {self.output_file}")
            user_input = input("Do you want to overwrite it? (y/n): ").strip().lower()
            if user_input != 'y':
                print("Aborting. Please move or rename the existing JSON file.")
                sys.exit(0)
            else:
                print("Overwriting existing JSON file...")
        # Initialize an empty JSON structure
        with open(self.output_file, 'w') as f:
            json.dump(self.results, f, indent=4)
        return

    def read_ROOT_file(self, angle_deg, root_file):
        """
        Reads the ROOT files for the specified angle, outputs temporary ASCII file for processing with pandas.
        Args:
            angle_deg - integer value for angle of ROOT file being read.
            root_file - string corresponding to ROOT file being read.
        Return values:
            txt_file - string corresponding to temporary ASCII file being created for reading into pandas DataFrame.
        """
        if self.debug:
            time_start = timer.time()
            print(f"Reading {root_file}...")
        cuts = f"trackPDG == 2112 || trackPDG == -11 || trackPDG == 22 || trackPDG == {self.alpha_code} || trackPDG == {self.triton_code}"
        macro_content = f"""
void readFiducial(const char* filename) {{
  TFile *_file0 = TFile::Open(filename);
  if (!_file0 || _file0->IsZombie()) {{ return; }}
  auto T = (TTree*)_file0->Get("output");
  T->SetScanField(-1);
  const char* columns = "trackPDG : trackProcess : mcx : mcy : mcz : trackPosX : trackPosY : trackPosZ : trackTime : trackKE";
  const char* cuts = "{cuts}";
  T->Scan(columns, cuts, "colsize=25 precision=9 col=::20.10");
}}
"""
        with open(self.macro_path, "w") as f:
            f.write(macro_content)
        print(f"Reading data from: {self.data_dir}/{root_file} ...")
        txt_file = "angle_data.txt"
        cmd = f'root -l -q -b "{self.macro_path}(\\"{root_file}\\")" > "{txt_file}"'
        subprocess.run(cmd, shell=True, check=True)
        # Clean up headers and '*' separators from ASCII file
        subprocess.run(f"sed -i '1,3d' {txt_file}", shell=True)
        subprocess.run(f"sed -i '$d' {txt_file}", shell=True)
        subprocess.run(f"sed -i 's/*//g' {txt_file}", shell=True)
        if self.debug:
            time_ROOT_to_ASCII = timer.time() - time_start
            time_total = timer.time() - self.time_start
            print(f"{root_file} processed. Processing time: {time_ROOT_to_ASCII:.3f}s.\nTotal time: {time_total:.3f}s.")
        return txt_file

    def extract_li6_data(self, data_file):
        """
        Reads an ASCII file and parses it into a pandas DataFrame.
        Args:
            data_file - string of name of ASCII file to read
        Return values:
            li6_df - pandas DataFrame containing the columns and entries of the ASCII file, filtered for captures on lithium-6
        """
        col_names = ['Row', 'Instance', 'trackPDG', 'trackProcess', 'mcx', 'mcy', 'mcz', 'trackPosX', 'trackPosY', 'trackPosZ', 'trackTime', 'trackKE']
        if self.debug:
            time_start = timer.time()
            print(f"Reading {data_file} into pandas dataframe...")
        try:
            angle_df = pd.read_csv(data_file, delim_whitespace=True, skiprows=1, header=0, skipinitialspace=True, names=col_names)
            li6_rows = angle_df.groupby('Row')['trackPDG'].apply(
                lambda x: (self.alpha_code in x.values) and (self.triton_code in x.values)
            )
            filtered_events = li6_rows[li6_rows == True].index.tolist()
            num_caps = len(filtered_events)
            print(f"Number of lithium 6 captures found: {num_caps}")
            li6_df = angle_df[angle_df['Row'].isin(filtered_events)].copy()
            # 2. Map coordinates to Voxels
            li6_df['voxelX'] = np.floor((li6_df['trackPosX'] - self.offset) / self.step_size)
            li6_df['voxelY'] = np.floor((li6_df['trackPosY'] - self.offset) / self.step_size)
            li6_df['voxelZ'] = np.floor((li6_df['trackPosZ'] - self.offset) / self.step_size)
            # 3. TRUE ENERGY DEPOSITION CALCULATION
            # Sort sequentially by Event -> Particle -> Step Number (Instance)
            li6_df = li6_df.sort_values(by=['Row', 'trackPDG', 'Instance'])
            # Shift trackKE down by 1 row within the same track to get KE_prev
            li6_df['KE_prev'] = li6_df.groupby(['Row', 'trackPDG'])['trackKE'].shift(1)
            # True Edep = KE before the step - KE after the step
            li6_df['edep'] = li6_df['KE_prev'] - li6_df['trackKE']
            # The first step of any particle has no previous KE (NaN). We fill with 0.
            # Clip at 0 to prevent negative energy fluctuations.
            li6_df['edep'] = li6_df['edep'].fillna(0).clip(lower=0)
            if self.debug:
                print(f"Original unfiltered data shape: {angle_df.shape}")
                print(f"Filtered Li-6 data shape:       {li6_df.shape}")
                print("\n--- Preview of Filtered Li-6 DataFrame ---")
                print(li6_df.head(15)) # Show the first 15 rows of the clean data
                print("------------------------------------------")            
        except Exception as e:
            print(f"Error processing data files: {e}\nExiting without completing binning...")
            sys.exit(1)
        if self.debug:
            df_timer = timer.time() - time_start
            total_time = timer.time() - self.time_start
            print(f"{li6_df} created in {df_timer:.3f}s.\nTotal running time: {total_time:.3f}s.")
        return li6_df

    def binEvents(self, df, angle):
        """
        Bins events in a 5 by 5 binning matrix by assigning random jitter to the starting point of the displacement vector 
        calculated from prompt and delayed energy deposition in the voxels with maximum energy depositions. Then the tip of 
        the vector is binned by number of segments away from the tail in x and y dimensions. The azimuthal angle is the only 
        angle of concern, so z coordinates are ignored.
        """
        if self.debug:
            time_start = timer.time()
            print(f"--- Starting binEvents for {angle} deg ---")
        if df is None or df.empty:
            print(f"Warning: DataFrame is empty. Skipping binning for {angle} deg...")
            return None
        # --- Initialize all possible bins to 0 ---
        json_friendly_bins = {}
        for dx in range(-2, 3):
            for dy in range(-2, 3):
                json_friendly_bins[f"{dx},{dy}"] = 0
        if self.debug:
            print(f"Binning matrix initialized with 0 counts:\n{json_friendly_bins}")
        try:
            # 1. Separate Prompt and Delayed Events using PDG Codes and Time as backup
            # Positron = -11, Alpha = 1000020040, Triton = 1000010030
            # We use getattr to safely fetch class properties if they exist, or default to standard PDG codes
            positron_code = getattr(self, 'positron_code', -11)
            alpha_code = getattr(self, 'alpha_code', 1000020040)
            triton_code = getattr(self, 'triton_code', 1000010030)
            # Prompt: Positrons OR events very early in time (< 1000 ns)
            prompt_mask = (df['trackPDG'] == positron_code) | (df['trackTime'] < 1000)
            prompt_events = df[prompt_mask].copy()
            # Delayed: Alpha/Triton from capture OR events late in time (>= 1000 ns)
            delayed_mask = (df['trackPDG'].isin([alpha_code, triton_code])) | (df['trackTime'] >= 1000)
            delayed_events = df[delayed_mask].copy()
            if self.debug:
                print(f"Found {len(prompt_events)} prompt tracks and {len(delayed_events)} delayed tracks.")
            if prompt_events.empty or delayed_events.empty:
                print("Warning: Missing prompt or delayed events. Cannot correlate.")
                return None                
            # 2. PROMPT: Find Voxel with Max True Edep per event
            p_voxel_edeps = prompt_events.groupby(['Row', 'voxelX', 'voxelY', 'voxelZ'])['edep'].sum().reset_index()
            p_max_idx = p_voxel_edeps.groupby('Row')['edep'].idxmax()
            p_max_voxels = p_voxel_edeps.loc[p_max_idx]               
            # 3. DELAYED: Find Voxel with Max True Edep per event
            d_voxel_edeps = delayed_events.groupby(['Row', 'voxelX', 'voxelY', 'voxelZ'])['edep'].sum().reset_index()
            d_max_idx = d_voxel_edeps.groupby('Row')['edep'].idxmax()
            d_max_voxels = d_voxel_edeps.loc[d_max_idx]       
            # 4. MERGE and calculate offsets
            merged = pd.merge(p_max_voxels, d_max_voxels, on='Row', suffixes=('_p', '_d'))
            if merged.empty:
                print("Warning: Merged DataFrame is empty. No rows have BOTH prompt and delayed events.")
                return None                
            # Calculate displacement in voxels
            merged['deltaX'] = merged['voxelX_d'] - merged['voxelX_p']
            merged['deltaY'] = merged['voxelY_d'] - merged['voxelY_p']
            # 4a. Count number of Li-6 captures
            total_li6_raw = df['Row'].nunique() if 'Row' in df.columns else "Unknown"
            # 4b. Count captures that successfully matched a prompt and delayed signal
            initial_matched_captures = len(merged)
            # 4c. Filter the dataframe to only keep deltaX and deltaY between -2 and 2
            merged_filtered = merged[
                (merged['deltaX'] >= -2) & (merged['deltaX'] <= 2) &
                (merged['deltaY'] >= -2) & (merged['deltaY'] <= 2)
            ]        
            # 4d. Count final binned captures
            binned_captures = len(merged_filtered)
            # 5. BINNING: Count the occurrences of each (deltaX, deltaY) pair
            displacement_counts = merged_filtered.groupby(['deltaX', 'deltaY']).size().to_dict()
            # --- Update the dictionary with actual calculated counts ---
            for k, v in displacement_counts.items():
                key_str = f"{int(k[0])},{int(k[1])}"
                # Populate the count if it exists, otherwise it remains 0
                json_friendly_bins[key_str] = int(v)            
            if self.debug:
                bin_timer = timer.time() - time_start
                total_time = timer.time() - self.time_start
                print(f"\n--- Angle {angle} Binning Stats ---")
                print(f"Raw Li-6 captures extracted:           {total_li6_raw}")
                print(f"Correlated pairs (Prompt + Delayed):   {initial_matched_captures}")
                print(f"Captures successfully binned (<= 2):   {binned_captures}")
                print(f"Captures dropped (outside 5x5 grid):   {initial_matched_captures - binned_captures}")
                print(f"-----------------------------------\n")
                print(f"Processing time for {angle} deg: {bin_timer:.3f}s.\nTotal running time: {total_time:.3f}s.")                
            return json_friendly_bins            
        except Exception as e:
            print(f"Error during binEvents execution for {angle} deg: {e}")
            return None

    def saveToJSON(self, angle, matrix_data):
        """
        Appends the binned matrix for a specific angle to the JSON file.
        Args:
            angle - integer value of angle for matrix data.
            matrix_data - matrix data to be saved in JSON file.
        Return values:
            None.
        """
        with open(self.output_file, 'r+') as f:
            data = json.load(f)
            data["angles"][str(angle)] = matrix_data
            f.seek(0)
            json.dump(data, f, indent=4)
            f.truncate()
        return

if __name__ == "__main__":
    cnfs = createNuLatFiducialSet()
    cnfs.debug=False# Toggle debug mode with this
    # Prompt for overwrite before any calculations
    cnfs.configure()
    for angle in range(360):
        print(f"Processing {angle} deg...")
        # 1. Read ROOT and generate text file
        dat_file = cnfs.read_ROOT_file(angle, f"nulat_output_angle_{angle}.ntuple.root")
        # 2. Extract the Li6 data
        li6_data = cnfs.extract_li6_data(dat_file)
        # 3. Bin the events
        matrix_data = cnfs.binEvents(li6_data, angle)
        if cnfs.debug:
            print(f"Binning matrix created for {angle} deg angle:\n{matrix_data}")
        # 4. Save to JSON
        if matrix_data:
            cnfs.saveToJSON(angle, matrix_data)
        # 5. Delete the temporary text file to save disk space
        if dat_file and os.path.exists(dat_file):
            os.remove(dat_file)
    print(f"Successfully saved fiducial set to: {cnfs.output_file}")
